/**
 * IntTest configurator
 * idk what to write here it's just a swagger
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InternalApiAuthListPermResponseItem model module.
 * @module model/InternalApiAuthListPermResponseItem
 * @version 2.0
 */
class InternalApiAuthListPermResponseItem {
    /**
     * Constructs a new <code>InternalApiAuthListPermResponseItem</code>.
     * @alias module:model/InternalApiAuthListPermResponseItem
     */
    constructor() { 
        
        InternalApiAuthListPermResponseItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InternalApiAuthListPermResponseItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InternalApiAuthListPermResponseItem} obj Optional instance to populate.
     * @return {module:model/InternalApiAuthListPermResponseItem} The populated <code>InternalApiAuthListPermResponseItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InternalApiAuthListPermResponseItem();

            if (data.hasOwnProperty('desc')) {
                obj['desc'] = ApiClient.convertToType(data['desc'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} desc
 */
InternalApiAuthListPermResponseItem.prototype['desc'] = undefined;

/**
 * @member {Number} id
 */
InternalApiAuthListPermResponseItem.prototype['id'] = undefined;

/**
 * @member {String} name
 */
InternalApiAuthListPermResponseItem.prototype['name'] = undefined;






export default InternalApiAuthListPermResponseItem;

