/**
 * IntTest configurator
 * idk what to write here it's just a swagger
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InternalApiAuthUpdateUserRequest model module.
 * @module model/InternalApiAuthUpdateUserRequest
 * @version 2.0
 */
class InternalApiAuthUpdateUserRequest {
    /**
     * Constructs a new <code>InternalApiAuthUpdateUserRequest</code>.
     * @alias module:model/InternalApiAuthUpdateUserRequest
     */
    constructor() { 
        
        InternalApiAuthUpdateUserRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InternalApiAuthUpdateUserRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InternalApiAuthUpdateUserRequest} obj Optional instance to populate.
     * @return {module:model/InternalApiAuthUpdateUserRequest} The populated <code>InternalApiAuthUpdateUserRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InternalApiAuthUpdateUserRequest();

            if (data.hasOwnProperty('role_ids')) {
                obj['role_ids'] = ApiClient.convertToType(data['role_ids'], ['Number']);
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Number>} role_ids
 */
InternalApiAuthUpdateUserRequest.prototype['role_ids'] = undefined;

/**
 * @member {String} username
 */
InternalApiAuthUpdateUserRequest.prototype['username'] = undefined;






export default InternalApiAuthUpdateUserRequest;

