/**
 * IntTest configurator
 * idk what to write here it's just a swagger
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InternalApiAuthRoleCreateResponse model module.
 * @module model/InternalApiAuthRoleCreateResponse
 * @version 2.0
 */
class InternalApiAuthRoleCreateResponse {
    /**
     * Constructs a new <code>InternalApiAuthRoleCreateResponse</code>.
     * @alias module:model/InternalApiAuthRoleCreateResponse
     */
    constructor() { 
        
        InternalApiAuthRoleCreateResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InternalApiAuthRoleCreateResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InternalApiAuthRoleCreateResponse} obj Optional instance to populate.
     * @return {module:model/InternalApiAuthRoleCreateResponse} The populated <code>InternalApiAuthRoleCreateResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InternalApiAuthRoleCreateResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
InternalApiAuthRoleCreateResponse.prototype['id'] = undefined;






export default InternalApiAuthRoleCreateResponse;

